- id: check-description-ends-with-period
  name: Check descriptions end with a period
  entry: dbt-yaml-description-validator --rule period
  language: python
  files: '(?i)schema\.ya?ml$'

- id: check-description-ends-with-period-fix
  name: Check descriptions end with a period (fix if failed)
  entry: dbt-yaml-description-validator --rule period --fix
  language: python
  files: '(?i)schema\.ya?ml$'

- id: check-description-starts-with-capital
  name: Check descriptions start with a capital letter
  entry: dbt-yaml-description-validator --rule capital
  language: python
  files: '(?i)schema\.ya?ml$'

- id: check-description-starts-with-capital-fix
  name: Check descriptions start with a capital letter (fix if failed)
  entry: dbt-yaml-description-validator --rule capital --fix
  language: python
  files: '(?i)schema\.ya?ml$'

- id: check-description-starts-with-article
  name: Check descriptions start with an article (The, A, An)
  entry: dbt-yaml-description-validator --rule article
  language: python
  files: '(?i)schema\.ya?ml$'

- id: check-description-no-symbols
  name: Check descriptions do not contain symbols
  entry: dbt-yaml-description-validator --rule symbols
  language: python
  files: '(?i)schema\.ya?ml$'

- id: check-description-double-spaces
  name: Check descriptions do not contain double spaces
  entry: dbt-yaml-description-validator --rule spaces
  language: python
  files: '(?i)schema\.ya?ml$'

- id: check-description-double-spaces-fix
  name: Check descriptions do not contain double spaces (fix if failed)
  entry: dbt-yaml-description-validator --rule spaces --fix
  language: python
  files: '(?i)schema\.ya?ml$'
