- id: check-description-ends-with-dot
  name: Check column descriptions ends with a dot
  description: Check the column descriptions in YAML files to ensure they end with a period.
  entry: check-description-ends-with-dot
  language: python
  files: '.*\.(yml|yaml)$'